### ISSUE TITLE
Error connecting to Redis issue

### ISSUE THREAD

**Issue by baraths84** [lalithr95/fuzzapi#35]
Hi - Can you please help on this issue(Trace log below).  Not able to start a scan.

Thanks Barath

redis (3.3.1) lib/redis/client.rb:345:in `rescue in establish_connection'
redis (3.3.1) lib/redis/client.rb:331:in`establish_connection'
redis (3.3.1) lib/redis/client.rb:101:in `block in connect'
redis (3.3.1) lib/redis/client.rb:293:in`with_reconnect'
redis (3.3.1) lib/redis/client.rb:100:in `connect'
newrelic_rpm (3.15.2.317) lib/new_relic/agent/instrumentation/redis.rb:66:in`block in connect'
newrelic_rpm (3.15.2.317) lib/new_relic/agent/datastores.rb:111:in `block in wrap'
newrelic_rpm (3.15.2.317) lib/new_relic/agent/method_tracer.rb:73:in`block in trace_execution_scoped'
newrelic_rpm (3.15.2.317) lib/new_relic/agent/method_tracer_helpers.rb:82:in `trace_execution_scoped'
newrelic_rpm (3.15.2.317) lib/new_relic/agent/method_tracer.rb:71:in`trace_execution_scoped'
newrelic_rpm (3.15.2.317) lib/new_relic/agent/datastores.rb:108:in `wrap'
newrelic_rpm (3.15.2.317) lib/new_relic/agent/instrumentation/redis.rb:65:in`connect'
redis (3.3.1) lib/redis/client.rb:364:in `ensure_connected'
redis (3.3.1) lib/redis/client.rb:221:in`block in process'
redis (3.3.1) lib/redis/client.rb:306:in `logging'
redis (3.3.1) lib/redis/client.rb:220:in`process'
redis (3.3.1) lib/redis/client.rb:187:in `call_pipelined'
redis (3.3.1) lib/redis/client.rb:157:in`block in call_pipeline'
redis (3.3.1) lib/redis/client.rb:293:in `with_reconnect'
redis (3.3.1) lib/redis/client.rb:155:in`call_pipeline'
newrelic_rpm (3.15.2.317) lib/new_relic/agent/instrumentation/redis.rb:58:in `block in call_pipeline'
newrelic_rpm (3.15.2.317) lib/new_relic/agent/datastores.rb:111:in`block in wrap'
newrelic_rpm (3.15.2.317) lib/new_relic/agent/method_tracer.rb:73:in `block in trace_execution_scoped'
newrelic_rpm (3.15.2.317) lib/new_relic/agent/method_tracer_helpers.rb:82:in`trace_execution_scoped'
newrelic_rpm (3.15.2.317) lib/new_relic/agent/method_tracer.rb:71:in `trace_execution_scoped'
newrelic_rpm (3.15.2.317) lib/new_relic/agent/datastores.rb:108:in`wrap'
newrelic_rpm (3.15.2.317) lib/new_relic/agent/instrumentation/redis.rb:57:in `call_pipeline'
redis (3.3.1) lib/redis.rb:2299:in`block in multi'
redis (3.3.1) lib/redis.rb:58:in `block in synchronize'
/Users/m716052/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/monitor.rb:214:in`mon_synchronize'
redis (3.3.1) lib/redis.rb:58:in `synchronize'
redis (3.3.1) lib/redis.rb:2291:in`multi'
sidekiq (4.1.4) lib/sidekiq/client.rb:178:in `block in raw_push'
connection_pool (2.2.0) lib/connection_pool.rb:64:in`block (2 levels) in with'
connection_pool (2.2.0) lib/connection_pool.rb:63:in `handle_interrupt'
connection_pool (2.2.0) lib/connection_pool.rb:63:in`block in with'
connection_pool (2.2.0) lib/connection_pool.rb:60:in `handle_interrupt'
connection_pool (2.2.0) lib/connection_pool.rb:60:in`with'
sidekiq (4.1.4) lib/sidekiq/client.rb:177:in `raw_push'
sidekiq (4.1.4) lib/sidekiq/client.rb:68:in`push'
sidekiq (4.1.4) lib/sidekiq/worker.rb:116:in `client_push'
sidekiq (4.1.4) lib/sidekiq/worker.rb:60:in`perform_async'
app/controllers/scans_controller.rb:49:in `create'
actionpack (4.2.7.1) lib/action_controller/metal/implicit_render.rb:4:in`send_action'
actionpack (4.2.7.1) lib/abstract_controller/base.rb:198:in `process_action'
actionpack (4.2.7.1) lib/action_controller/metal/rendering.rb:10:in`process_action'
actionpack (4.2.7.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (4.2.7.1) lib/active_support/callbacks.rb:117:in`call'
activesupport (4.2.7.1) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
activesupport (4.2.7.1) lib/active_support/callbacks.rb:505:in`call'
activesupport (4.2.7.1) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
activesupport (4.2.7.1) lib/active_support/callbacks.rb:778:in`_run_process_action_callbacks'
activesupport (4.2.7.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.7.1) lib/abstract_controller/callbacks.rb:19:in`process_action'
actionpack (4.2.7.1) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (4.2.7.1) lib/action_controller/metal/instrumentation.rb:32:in`block in process_action'
activesupport (4.2.7.1) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (4.2.7.1) lib/active_support/notifications/instrumenter.rb:20:in`instrument'
activesupport (4.2.7.1) lib/active_support/notifications.rb:164:in `instrument'
actionpack (4.2.7.1) lib/action_controller/metal/instrumentation.rb:30:in`process_action'
actionpack (4.2.7.1) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
activerecord (4.2.7.1) lib/active_record/railties/controller_runtime.rb:18:in`process_action'
actionpack (4.2.7.1) lib/abstract_controller/base.rb:137:in `process'
actionview (4.2.7.1) lib/action_view/rendering.rb:30:in`process'
actionpack (4.2.7.1) lib/action_controller/metal.rb:196:in `dispatch'
actionpack (4.2.7.1) lib/action_controller/metal/rack_delegation.rb:13:in`dispatch'
actionpack (4.2.7.1) lib/action_controller/metal.rb:237:in `block in action'
actionpack (4.2.7.1) lib/action_dispatch/routing/route_set.rb:74:in`dispatch'
actionpack (4.2.7.1) lib/action_dispatch/routing/route_set.rb:43:in `serve'
actionpack (4.2.7.1) lib/action_dispatch/journey/router.rb:43:in`block in serve'
actionpack (4.2.7.1) lib/action_dispatch/journey/router.rb:30:in `each'
actionpack (4.2.7.1) lib/action_dispatch/journey/router.rb:30:in`serve'
actionpack (4.2.7.1) lib/action_dispatch/routing/route_set.rb:817:in `call'
newrelic_rpm (3.15.2.317) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in`call'
newrelic_rpm (3.15.2.317) lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
newrelic_rpm (3.15.2.317) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in`call'
newrelic_rpm (3.15.2.317) lib/new_relic/rack/browser_monitoring.rb:32:in `traced_call'
newrelic_rpm (3.15.2.317) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in`call'
newrelic_rpm (3.15.2.317) lib/new_relic/rack/developer_mode.rb:48:in `traced_call'
newrelic_rpm (3.15.2.317) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in`call'
warden (1.2.6) lib/warden/manager.rb:35:in `block in call'
warden (1.2.6) lib/warden/manager.rb:34:in`catch'
warden (1.2.6) lib/warden/manager.rb:34:in `call'
newrelic_rpm (3.15.2.317) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in`call'
rack (1.6.4) lib/rack/etag.rb:24:in `call'
newrelic_rpm (3.15.2.317) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in`call'
rack (1.6.4) lib/rack/conditionalget.rb:38:in `call'
newrelic_rpm (3.15.2.317) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in`call'
rack (1.6.4) lib/rack/head.rb:13:in `call'
newrelic_rpm (3.15.2.317) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in`call'
actionpack (4.2.7.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
newrelic_rpm (3.15.2.317) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in`call'
actionpack (4.2.7.1) lib/action_dispatch/middleware/flash.rb:260:in `call'
newrelic_rpm (3.15.2.317) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in`call'
rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.6.4) lib/rack/session/abstract/id.rb:220:in`call'
newrelic_rpm (3.15.2.317) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
actionpack (4.2.7.1) lib/action_dispatch/middleware/cookies.rb:560:in`call'
newrelic_rpm (3.15.2.317) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
activerecord (4.2.7.1) lib/active_record/query_cache.rb:36:in`call'
newrelic_rpm (3.15.2.317) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
activerecord (4.2.7.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in`call'
newrelic_rpm (3.15.2.317) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
activerecord (4.2.7.1) lib/active_record/migration.rb:377:in`call'
newrelic_rpm (3.15.2.317) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
actionpack (4.2.7.1) lib/action_dispatch/middleware/callbacks.rb:29:in`block in call'
activesupport (4.2.7.1) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
activesupport (4.2.7.1) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
activesupport (4.2.7.1) lib/active_support/callbacks.rb:81:in`run_callbacks'
actionpack (4.2.7.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
newrelic_rpm (3.15.2.317) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in`call'
actionpack (4.2.7.1) lib/action_dispatch/middleware/reloader.rb:73:in `call'
newrelic_rpm (3.15.2.317) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in`call'
actionpack (4.2.7.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
newrelic_rpm (3.15.2.317) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in`call'
rollbar (2.8.3) lib/rollbar/middleware/rails/rollbar.rb:24:in `block in call'
rollbar (2.8.3) lib/rollbar.rb:948:in`scoped'
rollbar (2.8.3) lib/rollbar/middleware/rails/rollbar.rb:22:in `call'
newrelic_rpm (3.15.2.317) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in`call'
actionpack (4.2.7.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
rollbar (2.8.3) lib/rollbar/middleware/rails/show_exceptions.rb:22:in`call_with_rollbar'
newrelic_rpm (3.15.2.317) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
web-console (2.3.0) lib/web_console/middleware.rb:28:in`block in call'
web-console (2.3.0) lib/web_console/middleware.rb:18:in `catch'
web-console (2.3.0) lib/web_console/middleware.rb:18:in`call'
newrelic_rpm (3.15.2.317) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
actionpack (4.2.7.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in`call'
newrelic_rpm (3.15.2.317) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
railties (4.2.7.1) lib/rails/rack/logger.rb:38:in`call_app'
railties (4.2.7.1) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:68:in`block in tagged'
activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:68:in`tagged'
railties (4.2.7.1) lib/rails/rack/logger.rb:20:in `call'
newrelic_rpm (3.15.2.317) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in`call'
actionpack (4.2.7.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
newrelic_rpm (3.15.2.317) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in`call'
rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
newrelic_rpm (3.15.2.317) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in`call'
rack (1.6.4) lib/rack/runtime.rb:18:in `call'
newrelic_rpm (3.15.2.317) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in`call'
activesupport (4.2.7.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
newrelic_rpm (3.15.2.317) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in`call'
rack (1.6.4) lib/rack/lock.rb:17:in `call'
newrelic_rpm (3.15.2.317) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in`call'
actionpack (4.2.7.1) lib/action_dispatch/middleware/static.rb:120:in `call'
newrelic_rpm (3.15.2.317) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in`call'
rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
newrelic_rpm (3.15.2.317) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in`call'
railties (4.2.7.1) lib/rails/engine.rb:518:in `call'
railties (4.2.7.1) lib/rails/application.rb:165:in`call'
newrelic_rpm (3.15.2.317) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
rack (1.6.4) lib/rack/content_length.rb:15:in`call'
puma (3.4.0) lib/puma/configuration.rb:224:in `call'
puma (3.4.0) lib/puma/server.rb:569:in`handle_request'
puma (3.4.0) lib/puma/server.rb:406:in `process_client'
puma (3.4.0) lib/puma/server.rb:271:in`block in run'
puma (3.4.0) lib/puma/thread_pool.rb:114:in `block in spawn_thread'

**Comment by lalithr95** [comment]
@baraths84 Error is due to `redis-server`. Probably you didn't start redis server. Run `redis-server` in new terminal. Then run sidekiq command `bundle exec sidekiq`.

**Comment by baraths84** [comment]
Thanks that got resolved. I started to test it via Sample DVWS http://localhost/dvws/vulnerabilities/xxe2/server.php (GET request)  . The scan is performed with spinner showing up but "processing" of scans is  not getting completed..  Is there anything i should tune to get this working. Please advise

**Comment by baraths84** [comment]
I meant POST for - http://localhost/dvws/vulnerabilities/xxe2/server.php . Do i need to provide any headers . It would be great if you add a screen shot before the click of  the scan in the Readme. Finding it difficult to recall the steps from the appsec session.

**Comment by abhijeth** [comment]
Barath, you need to specify headers & parameters too :)

**Comment by baraths84** [comment]
I tried that too. But no luck. It would be helpful for first time users -  if you share the pre-steps/screeshot for a sample scan with headers and parameters . Eg. for the same DVWS/server.php example you have in the Readme.

**Comment by baraths84** [comment]
Hi @lalithr95 @abhijeth   - Can you  please help on this .

**Comment by lalithr95** [comment]
@baraths84 I'm updating documentation with detailed steps and screenshot to setup, run a scan

Thanks!

**Comment by dimpol** [comment]
Any expected date for the documentation or example? I am using header and parameter as they appear on burp but not luck.... An full scan example with headers and parameters would be really great. The tool seems great by the way...

**Comment by abhijeth** [comment]
Is your issue resolve @baraths84

**Comment by baraths84** [comment]
Hi @abhijeth  no not yet.. waiting on documentation updates from @lalithr95 . That will help.

**Comment by lalithr95** [comment]
Headsup @baraths84 
I have updated ruby version to 2.3.0 and fixed docker issues in #44 This should fix the issue.

Apologies for delay in response. Thanks for trying tool
