### ISSUE TITLE
Ubuntu Mate 16.10 Docker-compose up issue

### ISSUE THREAD

**Issue by Os3r3um** [lalithr95/fuzzapi#43]
Hi mate, 

I'm trying to get this one up and running. Got installed docker and I'm trying to spin up the instance. This is what I'm getting: 

"
d@ubuntu:~/Desktop/fuzzapi$ sudo docker-compose up
Starting fuzzapi_redis_1
Building web
Step 1 : FROM ruby:2.2
 ---> b068a763181d
Step 2 : RUN apt-get update && apt-get install -y   build-essential   nodejs
 ---> Running in c0dd0b2723fc
Err http://deb.debian.org jessie InRelease
  
Err http://security.debian.org jessie/updates InRelease
  
Err http://deb.debian.org jessie-updates InRelease
  
Err http://deb.debian.org jessie Release.gpg
  Could not resolve 'deb.debian.org'
Err http://security.debian.org jessie/updates Release.gpg
  Could not resolve 'security.debian.org'
Err http://deb.debian.org jessie-updates Release.gpg
  Could not resolve 'deb.debian.org'
Reading package lists...
W: Failed to fetch http://deb.debian.org/debian/dists/jessie/InRelease  

W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/InRelease  

W: Failed to fetch http://security.debian.org/dists/jessie/updates/InRelease  

W: Failed to fetch http://deb.debian.org/debian/dists/jessie/Release.gpg  Could not resolve 'deb.debian.org'

W: Failed to fetch http://security.debian.org/dists/jessie/updates/Release.gpg  Could not resolve 'security.debian.org'

W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/Release.gpg  Could not resolve 'deb.debian.org'

W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package build-essential
E: Unable to locate package nodejs
ERROR: Service 'web' failed to build: The command '/bin/sh -c apt-get update && apt-get install -y   build-essential   nodejs' returned a non-zero code: 100
"
Any ideas why is going for jessie updates?

Cheers.

**Comment by lalithr95** [comment]
@Os3r3um I have updated ruby to 2.3.0 and fixed docker issues. #44 

Thanks for trying tool. Let me know if you can setup easily with new code.
