### ISSUE TITLE
Socket Error in scan controller 

### ISSUE THREAD

**Issue by arthuragnar** [lalithr95/fuzzapi#48]
Getting socket error. Cannot resolve addrinfo.
![screenshot from 2017-01-04 02-40-32](https://cloud.githubusercontent.com/assets/10372078/21634749/6cb201fa-d27f-11e6-897a-3f0c28ab1589.png)

**Comment by arthuragnar** [comment]
Issue is resolved. The issue is because of redis-server. I have to externally install redis-server and  run sidekiq. 
Do:  
     Sudo apt-get install redis-server 
     redis-server (On one terminal)
     redis-cli(on other terminal)

Now run the command:  
       export REDIS_URL=redis://127.0.0.1:6379/0 && bundle exec sidekiq

**Comment by Et0hacker** [comment]
everything tried but getting same error
@arthuragnar @lalithr95 @nkpanda
