### ISSUE TITLE
How does the app expects raw headers?

### ISSUE THREAD

**Issue by mmat11** [lalithr95/fuzzapi#57]
I keep getting 'TID-ow1senkf8 WARN: ArgumentError: invalid cookie name' from Sidekiq because I probably fail to submit raw headers in the correct way.
All I do is putting headers this way:

![fuzzapi](https://user-images.githubusercontent.com/9884419/27325924-3d91d36a-55aa-11e7-9583-de1f53d8b1cd.png)

**Comment by lalithr95** [comment]
@mmat11 Fuzzapi is designed to have cookies separate from headers. You'll need to keep cookies inside cookies field. Please reopen the issue if it error still persists.
